-- Assignment-specific schema for Bookstore
-- This matches the exact requirements from the assignment

-- Drop existing tables if they exist
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS BOOK_AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS CUSTOMERS;

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    AUTHOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE,
    ROYALTY REAL DEFAULT 0.0
);

-- Create BOOKS table
CREATE TABLE BOOKS (
    ISBN TEXT PRIMARY KEY CHECK(LENGTH(ISBN) = 10),
    TITLE TEXT NOT NULL,
    PRICE REAL NOT NULL CHECK(PRICE >= 0),
    QUANTITY_SOLD INTEGER DEFAULT 0 CHECK(QUANTITY_SOLD >= 0)
);

-- Create BOOK_AUTHORS junction table (many-to-many relationship)
CREATE TABLE BOOK_AUTHORS (
    ISBN TEXT NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PERCENTAGE REAL NOT NULL CHECK(PERCENTAGE > 0 AND PERCENTAGE <= 100),
    PRIMARY KEY (ISBN, AUTHOR_ID),
    FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_book_authors_isbn ON BOOK_AUTHORS(ISBN);
CREATE INDEX idx_book_authors_author ON BOOK_AUTHORS(AUTHOR_ID);
CREATE INDEX idx_books_title ON BOOKS(TITLE);
CREATE INDEX idx_authors_name ON AUTHORS(NAME);

-- Trigger to update author royalty when book data changes
CREATE TRIGGER update_author_royalty_insert
AFTER INSERT ON BOOK_AUTHORS
BEGIN
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = NEW.AUTHOR_ID
    )
    WHERE AUTHOR_ID = NEW.AUTHOR_ID;
END;

CREATE TRIGGER update_author_royalty_update
AFTER UPDATE ON BOOK_AUTHORS
BEGIN
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = NEW.AUTHOR_ID
    )
    WHERE AUTHOR_ID = NEW.AUTHOR_ID;
    
    -- Also update old author if AUTHOR_ID changed
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = OLD.AUTHOR_ID
    )
    WHERE AUTHOR_ID = OLD.AUTHOR_ID AND OLD.AUTHOR_ID != NEW.AUTHOR_ID;
END;

CREATE TRIGGER update_author_royalty_delete
AFTER DELETE ON BOOK_AUTHORS
BEGIN
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = OLD.AUTHOR_ID
    )
    WHERE AUTHOR_ID = OLD.AUTHOR_ID;
END;

CREATE TRIGGER update_royalty_on_quantity_change
AFTER UPDATE OF QUANTITY_SOLD ON BOOKS
BEGIN
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = AUTHORS.AUTHOR_ID
    );
END;

CREATE TRIGGER update_royalty_on_price_change
AFTER UPDATE OF PRICE ON BOOKS
BEGIN
    UPDATE AUTHORS 
    SET ROYALTY = (
        SELECT COALESCE(SUM(
            (B.PRICE * BA.PERCENTAGE / 100.0 * B.QUANTITY_SOLD) / 
            (SELECT COUNT(*) FROM BOOK_AUTHORS WHERE ISBN = B.ISBN)
        ), 0)
        FROM BOOKS B
        JOIN BOOK_AUTHORS BA ON B.ISBN = BA.ISBN
        WHERE BA.AUTHOR_ID = AUTHORS.AUTHOR_ID
    );
END;