-- SQLite Schema for Bookstore Project
-- This script creates the database schema for the PHP Bookstore application using SQLite

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    AUTHOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    BIOGRAPHY TEXT
);

-- Create BOOKS table
CREATE TABLE BOOKS (
    BOOK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    ISBN TEXT, -- ISBN can be 10 or 13 digits
    GENRE TEXT,
    PUBLISHED_YEAR INTEGER,
    PRICE REAL NOT NULL,
    STOCK INTEGER,
    EDITION TEXT,
    COVER_URL TEXT,
    DESCRIPTION TEXT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Create BOOK_AUTHORS table to support multiple authors per book and royalty percentages
CREATE TABLE BOOK_AUTHORS (
    BOOK_AUTHOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOK_ID INTEGER NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PERCENTAGE REAL NOT NULL DEFAULT 0.10,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Index for quick lookups
CREATE INDEX idx_book_authors_book ON BOOK_AUTHORS(BOOK_ID);
CREATE INDEX idx_book_authors_author ON BOOK_AUTHORS(AUTHOR_ID);

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PHONE TEXT,
    ADDRESS TEXT
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TEXT DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT REAL NOT NULL,
    STATUS TEXT DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Create ORDER_ITEMS table
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORDER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE REAL NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

-- Create indexes for better performance
CREATE INDEX idx_books_author ON BOOKS(AUTHOR_ID);
CREATE INDEX idx_books_title ON BOOKS(TITLE);
CREATE INDEX idx_orders_customer ON ORDERS(CUSTOMER_ID);
CREATE INDEX idx_orders_date ON ORDERS(ORDER_DATE);
CREATE INDEX idx_order_items_order ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX idx_order_items_book ON ORDER_ITEMS(BOOK_ID);
CREATE INDEX idx_customers_email ON CUSTOMERS(EMAIL);

-- New tables for royalty history and cached stats (safe to create if missing)
CREATE TABLE IF NOT EXISTS AUTHOR_STATS (
    AUTHOR_ID INTEGER PRIMARY KEY,
    TOTAL_ROYALTY REAL NOT NULL DEFAULT 0.0,
    LAST_CALC_AT TEXT DEFAULT CURRENT_TIMESTAMP,
    PROJECTED_YEAR REAL DEFAULT 0.0,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS ROYALTY_TRANSACTIONS (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    BOOK_ID INTEGER,
    ORDER_ID INTEGER,
    AMOUNT REAL NOT NULL,
    CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
    STATUS TEXT DEFAULT 'Pending',
    NOTE TEXT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE INDEX IF NOT EXISTS idx_royalty_transactions_author ON ROYALTY_TRANSACTIONS(AUTHOR_ID);

-- Optional: Sample data insertion (uncomment to insert sample data)
/*
-- Insert sample authors
INSERT INTO AUTHORS (NAME, BIOGRAPHY) VALUES ('J.K. Rowling', 'British author best known for the Harry Potter series.');
INSERT INTO AUTHORS (NAME, BIOGRAPHY) VALUES ('George Orwell', 'English novelist and essayist.');

-- Insert sample books
INSERT INTO BOOKS (TITLE, AUTHOR_ID, ISBN, GENRE, PUBLISHED_YEAR, PRICE, STOCK, EDITION)
VALUES ('Harry Potter and the Philosopher''s Stone', 1, '0747532699', 'Fantasy', 1997, 19.99, 100, '1st Edition');

INSERT INTO BOOKS (TITLE, AUTHOR_ID, ISBN, GENRE, PUBLISHED_YEAR, PRICE, STOCK, EDITION)
VALUES ('1984', 2, '0451524934', 'Dystopian', 1949, 14.99, 50, '1st Edition');

-- Insert sample customers
INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE, ADDRESS)
VALUES ('John Doe', 'john.doe@example.com', '+1234567890', '123 Main St, Anytown, USA');

-- Insert sample order
INSERT INTO ORDERS (CUSTOMER_ID, TOTAL_AMOUNT, STATUS)
VALUES (1, 34.98, 'Pending');

-- Insert sample order items
INSERT INTO ORDER_ITEMS (ORDER_ID, BOOK_ID, QUANTITY, PRICE)
VALUES (1, 1, 1, 19.99);

INSERT INTO ORDER_ITEMS (ORDER_ID, BOOK_ID, QUANTITY, PRICE)
VALUES (1, 2, 1, 14.99);
*/